// Complete zodiac data with real astrological information
export const zodiacDetailedData = {
  Aries: {
    element: "Fire",
    rulingPlanet: "Mars",
    quality: "Cardinal",
    luckyDay: "Tuesday",
    luckyNumbers: [1, 9, 17],
    luckyColors: ["Red", "Scarlet", "Carmine"],
    luckyGemstone: "Diamond",
    strengths: ["Courageous", "Determined", "Confident", "Enthusiastic", "Optimistic", "Honest", "Passionate"],
    weaknesses: ["Impatient", "Moody", "Short-tempered", "Impulsive", "Aggressive"],
    compatibility: {
      best: ["Leo", "Sagittarius", "Gemini", "Aquarius"],
      good: ["Aries", "Libra"],
      challenging: ["Cancer", "Capricorn"],
    },
    luckProfile: {
      bestHours: ["6:00 AM - 8:00 AM", "1:00 PM - 3:00 PM"],
      bestActivities: ["Starting new projects", "Physical exercise", "Competition", "Leadership roles"],
      avoidActivities: ["Long-term planning", "Detailed paperwork", "Waiting games"],
    },
    dailyAffirmations: [
      "I channel my passion into positive action.",
      "My courage inspires those around me.",
      "I lead with confidence and compassion.",
      "Every challenge is an opportunity for growth.",
    ],
  },
  Taurus: {
    element: "Earth",
    rulingPlanet: "Venus",
    quality: "Fixed",
    luckyDay: "Friday",
    luckyNumbers: [2, 6, 9, 12, 24],
    luckyColors: ["Green", "Pink", "White"],
    luckyGemstone: "Emerald",
    strengths: ["Reliable", "Patient", "Practical", "Devoted", "Responsible", "Stable"],
    weaknesses: ["Stubborn", "Possessive", "Uncompromising"],
    compatibility: {
      best: ["Virgo", "Capricorn", "Cancer", "Pisces"],
      good: ["Taurus", "Scorpio"],
      challenging: ["Leo", "Aquarius"],
    },
    luckProfile: {
      bestHours: ["10:00 AM - 12:00 PM", "7:00 PM - 9:00 PM"],
      bestActivities: ["Financial planning", "Gardening", "Cooking", "Art appreciation"],
      avoidActivities: ["Risky investments", "Sudden changes", "Rushed decisions"],
    },
    dailyAffirmations: [
      "I build my dreams on a foundation of patience.",
      "My persistence creates lasting success.",
      "I appreciate the beauty in everyday moments.",
      "Stability and growth coexist in my life.",
    ],
  },
  Gemini: {
    element: "Air",
    rulingPlanet: "Mercury",
    quality: "Mutable",
    luckyDay: "Wednesday",
    luckyNumbers: [5, 7, 14, 23],
    luckyColors: ["Yellow", "Light Green"],
    luckyGemstone: "Agate",
    strengths: ["Gentle", "Affectionate", "Curious", "Adaptable", "Quick learner"],
    weaknesses: ["Nervous", "Inconsistent", "Indecisive"],
    compatibility: {
      best: ["Libra", "Aquarius", "Aries", "Leo"],
      good: ["Gemini", "Sagittarius"],
      challenging: ["Virgo", "Pisces"],
    },
    luckProfile: {
      bestHours: ["8:00 AM - 10:00 AM", "3:00 PM - 5:00 PM"],
      bestActivities: ["Networking", "Writing", "Learning", "Short trips"],
      avoidActivities: ["Monotonous tasks", "Long-term commitments", "Isolation"],
    },
    dailyAffirmations: [
      "My curiosity leads me to wonderful discoveries.",
      "I communicate with clarity and kindness.",
      "My adaptability is my greatest strength.",
      "I embrace all aspects of my dynamic personality.",
    ],
  },
  Cancer: {
    element: "Water",
    rulingPlanet: "Moon",
    quality: "Cardinal",
    luckyDay: "Monday",
    luckyNumbers: [2, 7, 11, 16],
    luckyColors: ["White", "Silver", "Sea Green"],
    luckyGemstone: "Pearl",
    strengths: ["Tenacious", "Highly imaginative", "Loyal", "Emotional", "Sympathetic", "Persuasive"],
    weaknesses: ["Moody", "Pessimistic", "Suspicious", "Manipulative", "Insecure"],
    compatibility: {
      best: ["Scorpio", "Pisces", "Taurus", "Virgo"],
      good: ["Cancer", "Capricorn"],
      challenging: ["Aries", "Libra"],
    },
    luckProfile: {
      bestHours: ["9:00 AM - 11:00 AM", "6:00 PM - 8:00 PM"],
      bestActivities: ["Family gatherings", "Home improvement", "Cooking", "Nurturing others"],
      avoidActivities: ["Confrontations", "Public speaking", "Taking big risks"],
    },
    dailyAffirmations: [
      "My sensitivity is a gift that connects me to others.",
      "I create a safe haven wherever I go.",
      "My intuition guides me to the right decisions.",
      "I am worthy of the love I give to others.",
    ],
  },
  Leo: {
    element: "Fire",
    rulingPlanet: "Sun",
    quality: "Fixed",
    luckyDay: "Sunday",
    luckyNumbers: [1, 3, 10, 19],
    luckyColors: ["Gold", "Orange", "Red"],
    luckyGemstone: "Ruby",
    strengths: ["Creative", "Passionate", "Generous", "Warm-hearted", "Cheerful", "Humorous"],
    weaknesses: ["Arrogant", "Stubborn", "Self-centered", "Lazy", "Inflexible"],
    compatibility: {
      best: ["Aries", "Sagittarius", "Gemini", "Libra"],
      good: ["Leo", "Aquarius"],
      challenging: ["Taurus", "Scorpio"],
    },
    luckProfile: {
      bestHours: ["11:00 AM - 1:00 PM", "5:00 PM - 7:00 PM"],
      bestActivities: ["Creative projects", "Performing", "Leadership", "Romance"],
      avoidActivities: ["Background roles", "Criticism", "Routine tasks"],
    },
    dailyAffirmations: [
      "My light illuminates the path for others.",
      "I lead with generosity and warmth.",
      "My creativity knows no bounds.",
      "I deserve recognition for my authentic self.",
    ],
  },
  Virgo: {
    element: "Earth",
    rulingPlanet: "Mercury",
    quality: "Mutable",
    luckyDay: "Wednesday",
    luckyNumbers: [5, 14, 15, 23, 32],
    luckyColors: ["Grey", "Beige", "Pale Yellow"],
    luckyGemstone: "Sapphire",
    strengths: ["Loyal", "Analytical", "Kind", "Hardworking", "Practical"],
    weaknesses: ["Shyness", "Worry", "Overly critical", "All work and no play"],
    compatibility: {
      best: ["Taurus", "Capricorn", "Cancer", "Scorpio"],
      good: ["Virgo", "Pisces"],
      challenging: ["Gemini", "Sagittarius"],
    },
    luckProfile: {
      bestHours: ["7:00 AM - 9:00 AM", "2:00 PM - 4:00 PM"],
      bestActivities: ["Organizing", "Health routines", "Helping others", "Detail work"],
      avoidActivities: ["Chaos", "Impulsive decisions", "Overlooking details"],
    },
    dailyAffirmations: [
      "My attention to detail creates excellence.",
      "I am worthy of love, even when imperfect.",
      "My service to others brings me joy.",
      "I balance analysis with intuition.",
    ],
  },
  Libra: {
    element: "Air",
    rulingPlanet: "Venus",
    quality: "Cardinal",
    luckyDay: "Friday",
    luckyNumbers: [4, 6, 13, 15, 24],
    luckyColors: ["Pink", "Blue", "Lavender"],
    luckyGemstone: "Opal",
    strengths: ["Cooperative", "Diplomatic", "Gracious", "Fair-minded", "Social"],
    weaknesses: ["Indecisive", "Avoids confrontations", "Self-pity", "Holds grudges"],
    compatibility: {
      best: ["Gemini", "Aquarius", "Leo", "Sagittarius"],
      good: ["Libra", "Aries"],
      challenging: ["Cancer", "Capricorn"],
    },
    luckProfile: {
      bestHours: ["10:00 AM - 12:00 PM", "6:00 PM - 8:00 PM"],
      bestActivities: ["Socializing", "Art", "Negotiations", "Partnerships"],
      avoidActivities: ["Arguments", "Isolation", "Quick decisions"],
    },
    dailyAffirmations: [
      "I create harmony in all my relationships.",
      "My decisions reflect my inner truth.",
      "Beauty and balance flow through me.",
      "I am complete within myself.",
    ],
  },
  Scorpio: {
    element: "Water",
    rulingPlanet: "Pluto, Mars",
    quality: "Fixed",
    luckyDay: "Tuesday",
    luckyNumbers: [8, 11, 18, 22],
    luckyColors: ["Scarlet", "Red", "Rust"],
    luckyGemstone: "Topaz",
    strengths: ["Resourceful", "Brave", "Passionate", "Stubborn", "A true friend"],
    weaknesses: ["Distrusting", "Jealous", "Secretive", "Violent"],
    compatibility: {
      best: ["Cancer", "Pisces", "Virgo", "Capricorn"],
      good: ["Scorpio", "Taurus"],
      challenging: ["Leo", "Aquarius"],
    },
    luckProfile: {
      bestHours: ["12:00 PM - 2:00 PM", "8:00 PM - 10:00 PM"],
      bestActivities: ["Research", "Transformation", "Deep conversations", "Strategic planning"],
      avoidActivities: ["Superficiality", "Betrayal situations", "Sharing secrets"],
    },
    dailyAffirmations: [
      "My intensity is a source of power.",
      "I transform challenges into opportunities.",
      "My depth creates meaningful connections.",
      "I trust the process of constant renewal.",
    ],
  },
  Sagittarius: {
    element: "Fire",
    rulingPlanet: "Jupiter",
    quality: "Mutable",
    luckyDay: "Thursday",
    luckyNumbers: [3, 7, 9, 12, 21],
    luckyColors: ["Blue", "Purple", "Plum"],
    luckyGemstone: "Turquoise",
    strengths: ["Generous", "Idealistic", "Great sense of humor"],
    weaknesses: ["Promises more than can deliver", "Impatient", "Will say anything"],
    compatibility: {
      best: ["Aries", "Leo", "Libra", "Aquarius"],
      good: ["Sagittarius", "Gemini"],
      challenging: ["Virgo", "Pisces"],
    },
    luckProfile: {
      bestHours: ["9:00 AM - 11:00 AM", "4:00 PM - 6:00 PM"],
      bestActivities: ["Travel", "Learning", "Teaching", "Adventure sports"],
      avoidActivities: ["Routine", "Details", "Commitments that limit freedom"],
    },
    dailyAffirmations: [
      "My optimism opens doors everywhere.",
      "Adventure awaits in every moment.",
      "I spread wisdom and joy freely.",
      "My honesty creates authentic connections.",
    ],
  },
  Capricorn: {
    element: "Earth",
    rulingPlanet: "Saturn",
    quality: "Cardinal",
    luckyDay: "Saturday",
    luckyNumbers: [4, 8, 13, 22],
    luckyColors: ["Brown", "Black", "Grey"],
    luckyGemstone: "Garnet",
    strengths: ["Responsible", "Disciplined", "Self-control", "Good managers"],
    weaknesses: ["Know-it-all", "Unforgiving", "Condescending", "Expecting the worst"],
    compatibility: {
      best: ["Taurus", "Virgo", "Scorpio", "Pisces"],
      good: ["Capricorn", "Cancer"],
      challenging: ["Aries", "Libra"],
    },
    luckProfile: {
      bestHours: ["8:00 AM - 10:00 AM", "7:00 PM - 9:00 PM"],
      bestActivities: ["Career advancement", "Long-term planning", "Investing", "Building"],
      avoidActivities: ["Shortcuts", "Impulsive spending", "Neglecting health"],
    },
    dailyAffirmations: [
      "My discipline creates lasting success.",
      "I climb mountains one step at a time.",
      "My wisdom grows with each experience.",
      "I balance ambition with joy.",
    ],
  },
  Aquarius: {
    element: "Air",
    rulingPlanet: "Uranus, Saturn",
    quality: "Fixed",
    luckyDay: "Saturday",
    luckyNumbers: [4, 7, 11, 22, 29],
    luckyColors: ["Electric Blue", "Grey", "Ultramarine"],
    luckyGemstone: "Amethyst",
    strengths: ["Progressive", "Original", "Independent", "Humanitarian"],
    weaknesses: ["Runs from emotional expression", "Temperamental", "Uncompromising", "Aloof"],
    compatibility: {
      best: ["Gemini", "Libra", "Aries", "Sagittarius"],
      good: ["Aquarius", "Leo"],
      challenging: ["Taurus", "Scorpio"],
    },
    luckProfile: {
      bestHours: ["11:00 AM - 1:00 PM", "9:00 PM - 11:00 PM"],
      bestActivities: ["Innovation", "Social causes", "Technology", "Group activities"],
      avoidActivities: ["Conformity", "Emotional demands", "Traditional approaches"],
    },
    dailyAffirmations: [
      "My uniqueness is my contribution to the world.",
      "I innovate for the benefit of all.",
      "My independence strengthens my connections.",
      "I embrace both logic and emotion.",
    ],
  },
  Pisces: {
    element: "Water",
    rulingPlanet: "Neptune, Jupiter",
    quality: "Mutable",
    luckyDay: "Thursday",
    luckyNumbers: [3, 9, 12, 15, 18, 24],
    luckyColors: ["Mauve", "Lilac", "Purple", "Violet", "Sea Green"],
    luckyGemstone: "Aquamarine",
    strengths: ["Compassionate", "Artistic", "Intuitive", "Gentle", "Wise", "Musical"],
    weaknesses: ["Fearful", "Overly trusting", "Sad", "Desire to escape reality"],
    compatibility: {
      best: ["Cancer", "Scorpio", "Taurus", "Capricorn"],
      good: ["Pisces", "Virgo"],
      challenging: ["Gemini", "Sagittarius"],
    },
    luckProfile: {
      bestHours: ["7:00 AM - 9:00 AM", "5:00 PM - 7:00 PM"],
      bestActivities: ["Creative arts", "Meditation", "Healing", "Water activities"],
      avoidActivities: ["Harsh environments", "Confrontation", "Rigid schedules"],
    },
    dailyAffirmations: [
      "My intuition guides me to my highest path.",
      "I create beauty from my inner visions.",
      "My compassion heals myself and others.",
      "I am grounded even as I dream.",
    ],
  },
};

export type ZodiacDataKey = keyof typeof zodiacDetailedData;
